### ISSUE TITLE
Add an order of magnitude value for required data rates to operate different types of blockchain configurations

### ISSUE THREAD

**Issue by bretthenderson** [prototypo/blockchains-in-space#7]
**Reviewer 2 Comment**
I thought there was a bit of an inconsistency in the paper. On one hand, it talks about a relatively distant future where there are space economies and the use of blockchains makes a lot of sense, but on the other hand some short-term limitations about spacecraft technologies such as low throughput and low datarates are used to make arguments about selection of algorithms etc. Communication delays is an example of a factor that will not go away with any amount of new technologies, but the limitations in terms of compute and datarate are probably not going to be an issue in the relatively near future. Or if the authors think they are then they should provide numbers about the kinds of throughputs and datarates needed to operate blockchains in space so we can compare those to our predictions of where these technologies will be.

**Comment by drinkcoffee** [comment]
I will put this message here so we don't lose it.

I am working on my the analysis for issue 7: Order of magnitude value for required data rates to operate different types of blockchain configurations?
I am going to write out my guestimates here so everyone can weigh in here before I start putting in words / a table.
In the paper we talk about: Regular node, Mining node, Read-only node, Write request node.
Assume a network configuration:
Five mining nodes interconnected, each mining node connected to five regular nodes.
Each full node connected to three mining nodes and 10 write request nodes and 10 read only nodes.
Each write request node connected to one full node.
Each read only node connected to one full node.
Assume transactions are gossiped from write request nodes to full nodes, who flood to all mining nodes they know of, who flood to all mining nodes they know of.
Assume that mining nodes flood blocks (which the same transactions in them from the last line) to all mining and regular nodes they are attached to.
Assume write request nodes and read only nodes fetch only the information they need, but that this information is about the same size as a transaction.
For simplicity, assume all transactions come down a single path, rather than being spread across the different write request nodes.
Assume a transaction size of 10 Kb. Assume 20 transactions per second. Assume read nodes only want one transaction per second. Assume write nodes only submit one transaction per second.
Mining node: Each transaction is received once from full node, gossiped to 4 other miners, mined in a block and then gossiped as part of a block to the four other miners and to the five regular nodes. Each transaction communicated 14 times. 14 x 20 tps x 10 Kb/t = 2.8 Mbps.
Regular node: Each transaction is received from a write node, and gossiped to 3 mining, and then the block is communicated from 3 mining nodes and communicated with 10 write request nodes and 10 read only nodes.  Each transaction is communicated 27 times. 27 x 20 tps x 10 kb/t = 5.4 Mbps.
Write node: one transaction per second to write and one transaction per second for read. 2 x 1 tps x 10 Kb = 20 Kbps
Read only node: one transaction per second for read. 1 x 1 tps x 10 Kb = 10 Kbps
So, mining nodes and regular nodes are in the low Mbps, and the write and read only nodes are in the low tens of Kbps.
Does this seem approximately right? Should this be put into an appendix so people can re-produce the numbers and change the assumptions?

**Comment by prototypo** [comment]
Thanks @drinkcoffee. It does seem about right, and is worth trying to summarise in the main body. I’ll give that a go and point you to it for review, ok?

**Comment by saltiniroberto** [comment]
I miss how the number of times (like 14) that a transaction is sent is calculated.

**Comment by prototypo** [comment]
Added https://github.com/prototypo/blockchains-in-space/commit/68b4f9e2bb4821c977418ce585a9b166adde398a to address this issue.
